apiVersion: v1
kind: Service
metadata:
  name: tomcat-svc
  labels:
    app: tomcat
spec:
  type: NodePort
  sessionAffinity: ClientIP
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30010
  selector:
    app: tomcat
