kind: PersistentVolume
apiVersion: v1
metadata:
  name: tomcat-pv
  labels:
    type: local
spec:
  storageClassName: local-storage
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/data/tomcat/"
