kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    limits:
      storage: 5Gi
    requests:
      storage: 3Gi
  volumeName: local-pv1
