apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: flowfilerepository
      labels:
        type: local
    spec:
      storageClassName: local-storage
      capacity:
        storage: 5Gi
      accessModes:
        - ReadWriteOnce
      persistentVolumeReclaimPolicy: Retain
      hostPath:
        path: "/media/hdd/nifi"
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: databaserepository
      labels:
        type: local
    spec:
      storageClassName: local-storage
      capacity:
        storage: 5Gi
      accessModes:
        - ReadWriteOnce
      persistentVolumeReclaimPolicy: Retain
      hostPath:
        path: "/media/hdd/nifi"
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: contentrepository
      labels:
        type: local
    spec:
      storageClassName: local-storage
      capacity:
        storage: 5Gi
      accessModes:
        - ReadWriteOnce
      persistentVolumeReclaimPolicy: Retain
      hostPath:
        path: "/media/hdd/nifi"
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: provenancerepository
      labels:
        type: local
    spec:
      storageClassName: local-storage
      capacity:
        storage: 5Gi
      accessModes:
        - ReadWriteOnce
      persistentVolumeReclaimPolicy: Retain
      hostPath:
        path: "/media/hdd/nifi"
