apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es-node
  labels:
    component: elasticsearch
    role: node
spec:
  selector:
    matchLabels:
      component: elasticsearch
      role: node
  serviceName: elasticsearch
  replicas: 3
  template:
    metadata:
      labels:
        component: elasticsearch
        role: node
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox:1.27.2
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        env:
        - name: ES_JAVA_OPTS
          value: -Xms1g -Xmx1g
        - name: bootstrap.memory_lock
          value: "true"
        securityContext:
          privileged: true
      containers:
      - name: es-node
        image: elasticsearch:6.6.1
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - containerPort: 9300
          name: transport
        - containerPort: 9200
          name: http
        volumeMounts:
        - mountPath: /data
          name: storage
        - name: elasticsearch-yml
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
          subPath: elasticsearch.yml
      volumes:
        - name: elasticsearch-yml
          configMap:
            name: es-config-node
            items:
                - key: elasticsearch.yml
                  path: elasticsearch.yml
  volumeClaimTemplates:
  - metadata:
      name: storage
      labels:
        name: storage
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: sc-local
      resources:
        requests:
          storage: 30Gi
