kind: Service
apiVersion: v1
metadata:
  name: kafka-manager
  namespace: default
spec:
  type: NodePort
  selector:
    app: kafka-manager
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000
    nodePort: 30035
  sessionAffinity: ClientIP
