apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
  labels:
    app: kafka
spec:
  sessionAffinity: ClientIP
  type: NodePort
  ports:
  - port: 9094
    name: server
    nodePort: 30010
    protocol: TCP
  selector:
    app: kafka
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: kafka-svc
  replicas: 2
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        imagePullPolicy: Always
        image: wurstmeister/kafka:latest
        ports:
        - containerPort: 9094
          name: server
        env:
        - name: HOSTNAME_COMMAND
          value : "docker info | grep ^Name: | cut -d' ' -f 2"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zk-0.zk-svc.default.svc.cluster.local:2181,zk-1.zk-svc.default.svc.cluster.local:2181
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value : INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
        - name: KAFKA_ADVERTISED_LISTENERS
          value : INSIDE://:9092,OUTSIDE://_{HOSTNAME_COMMAND}:9094
        - name: KAFKA_LISTENERS
          value : INSIDE://:9092,OUTSIDE://:9094
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value : INSIDE
        volumeMounts:
        - name: datadir
          mountPath: /var/lib/kafka
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      storageClassName: local-storage
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
