apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-manager
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-manager
  template:
    metadata:
      labels:
        app: kafka-manager
    spec:
      containers:
      - name: kafka-manager
        image: sheepkiller/kafka-manager
        ports:
        - containerPort: 9000
        env:
        - name: ZK_HOSTS
          value: "zk-0.zk-svc.default.svc.cluster.local:2181,zk-1.zk-svc.default.svc.cluster.local:2181"
        command:
        - ./bin/kafka-manager
        - -Dhttp.port=9000
