apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx-dp  # tên pod
spec:
  replicas: 2   # số lượng pod
  selector:
    matchLabels:
      app: nginx
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: nginx    # set label cho các pod
    spec:
      containers:
        - name: nginx-pod   # tên container
          image: nginx    # docker images
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: "/usr/share/nginx/html"    # đường dẫn nginx root trong pod
              name: nginx-volume
            - mountPath: "/etc/nginx"     # đường dẫn config folder trong pod
              name: nginx-conf
      volumes:
        - name: nginx-volume      # tạo volumes từ pvc đã tạo
          persistentVolumeClaim:
            claimName: nginx-pvc    # tên pvc đã tạo
        - name: nginx-conf
          persistentVolumeClaim:
            claimName: nginx-pvc-conf
