kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-pvc   # tên pvc
spec:
  storageClassName: sc-local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: nginx-pv    # tên pv đã tạo
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nginx-pvc-conf
spec:
  storageClassName: sc-local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: nginx-pv-conf
