apiVersion: v1
kind: Service
metadata:
  name: nginx-svc   # tên service
  labels:
    app: nginx
spec:
  type: NodePort    # type service
  sessionAffinity: ClientIP
  ports:
  - protocol: TCP
    port: 80  # port public
    targetPort: 80  # port running container
    nodePort: 30030   # port service sẽ chạy trên nodes
  selector:
    app: nginx    # chọn hết các pod có label là "nginx"
