kind: PersistentVolume
apiVersion: v1
metadata:
  name: openresty-pv
  labels:
    type: local
spec:
  storageClassName: sc-local
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/data/openresty/html/"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: openresty-conf-pv
  labels:
    type: local
spec:
  storageClassName: sc-local
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/data/openresty/conf/"
