apiVersion: v1
kind: Service
metadata:
  name: openresty-svc
  labels:
    app: openresty
spec:
  type: NodePort
  sessionAffinity: ClientIP
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 80
    nodePort: 30011
  selector:
    app: openresty