kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: camunda-pvc
spec:
  storageClassName: sc-local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  volumeName: camunda-pv
