kind: PersistentVolume
apiVersion: v1
metadata:
  name: camunda-pv
  labels:
    type: local
spec:
  storageClassName: sc-local
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/data/camunda"
