apiVersion: v1
kind: Service
metadata:
  name: camunda-service
  labels:
    app: camunda
spec:
  type: NodePort
  selector:
    app: camunda
  ports:
  - name: bpm
    port: 8080
    protocol: TCP
    nodePort: 30020
  sessionAffinity: ClientIP
